name: white-house
adopt-info: white-house
summary: Using the magic of CSS, hack your world into a unique burst of color.
base: core22
architectures:
- amd64
confinement: strict
grade: stable

apps:
  white-house:
    extensions: [gnome]
    command: whitehouse/whitehouse.x86_64
    common-id: com.endlessnetwork.whitehouse
    environment:
      LD_LIBRARY_PATH: $SNAP/whitehouse/whitehouse_Data/Plugins/x86_64:$SNAP/whitehouse/whitehouse_Data/Mono/x86_64:$LD_LIBRARY_PATH
    plugs:
      - audio-playback
      - joystick
      - network

parts:
  white-house:
    plugin: nil
    source: https://github.com/endless-network/WhiteHouse_Binary.git
    parse-info: [com.endlessnetwork.whitehouse.appdata.xml]
    build-packages:
      - unzip
      - wget
      - jq
    override-pull: |
      craftctl default
      curl https://api.github.com/repos/endless-network/WhiteHouse_Binary/releases/latest | jq -r ".assets[0].browser_download_url" | xargs wget -O whitehouse.zip
      unzip whitehouse.zip -d temp
    override-build: |
      craftctl default
      # Grab latest release
      mkdir -p $CRAFT_PART_INSTALL/whitehouse
      cp temp/*/*.x86_64 $CRAFT_PART_INSTALL/whitehouse/whitehouse.x86_64
      cp -r temp/*/*_Data $CRAFT_PART_INSTALL/whitehouse/whitehouse_Data
      chmod +x $CRAFT_PART_INSTALL/whitehouse/whitehouse.x86_64
      # Metadata
      sed -i 's|Icon=com.endlessnetwork.whitehouse$|Icon=${SNAP}/meta/gui/icon.png|g' com.endlessnetwork.whitehouse.desktop
      sed -i 's|Exec=com.endlessnetwork.whitehouse.sh$|Exec=white-house|g' com.endlessnetwork.whitehouse.desktop
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp com.endlessnetwork.whitehouse_128.png $CRAFT_PART_INSTALL/meta/gui/icon.png
      cp com.endlessnetwork.whitehouse.desktop $CRAFT_PART_INSTALL/meta/gui/
      cp LICENSE $CRAFT_PART_INSTALL
